Repository cloud-native-toolkit/ibm-garage-cloud-cli, pull requests merged in 2021-02, with the labels that each got.

#101 update pull-secret to default namespace
  src/commands/pull-secret.ts
  src/services/namespace/namespace.ts
Labels: feature, minor

#102 clarify npm start
  README.md
  package.json
Labels: chore

#103 pipeline: Waits for deployment of event listener
  package.json
  src/api/kubectl/deployment.ts
  src/commands/namespace.ts
  src/commands/pull-secret.ts
  src/commands/register-pipeline.ts
  src/commands/vlan.ts
  src/services/register-pipeline/register-tekton-pipeline.ts
  src/util/logger.ts
Labels: bug, minor
