Repository cloud-native-toolkit/ibm-garage-cloud-cli, pull requests merged in 2021-03, with the labels that each got.

#111 pipeline: Adds support for Tekton Triggers v0.8.0 for webhook creation
  src/services/register-pipeline/register-tekton-pipeline.ts
Labels: feature, minor

#112 gitops: Allows git url to be passed as parameter
  src/commands/gitops.ts
  src/services/git-secret/create-git-secret.api.ts
Labels: feature, minor

#113 Updates moodule dependencies
  package-lock.json
  package.json
  src/api/ibmcloud/login.ts
  src/api/ibmcloud/vlans.api.ts
  src/api/ibmcloud/zones.api.ts
  src/api/kubectl/from-file.api.ts
  src/api/kubectl/from-file.impl.ts
  src/api/kubectl/kubernetes-resource-manager.ts
  src/api/kubectl/namespace.ts
  src/services/console/console.api.ts
  src/services/create-service-account/create-service-account.api.ts
  src/services/create-webhook/create-webhook.api.ts
  src/services/credentials/credentials.api.ts
  src/services/dashboard/get-dashboard-url.api.ts
  src/services/enable/enable.api.ts
  src/services/endpoints/endpoints.api.ts
  src/services/generate-token/generate-token.ts
  src/services/git-secret/create-git-secret.api.ts
  src/services/git-secret/git-parameters.api.ts
  src/services/git-secret/git-secret.api.ts
  src/services/jenkins-auth/config-jenkins-auth.api.ts
  src/services/jenkins-auth/config-jenkins-auth.ts
  src/services/login/ibmcloud-login.ts
  src/services/namespace/namespace.api.ts
  src/services/register-pipeline/jenkins/register-pipeline-type.ts
  src/services/register-pipeline/register-pipeline.api.ts
  src/services/vlan/get-vlan.api.ts
  src/services/yq/yq-write.api.ts
  src/util/question-builder.api.ts
  src/util/timer.ts
Labels: chore, patch

#114 Update npm-publish.yaml
  .github/workflows/npm-publish.yaml
Labels: chore

#115 Fix release publish by using PAT
  .github/workflows/release.yaml
Labels: chore

#117 Updates references to the git org in urls
  README.md
  src/commands/enable.ts
Labels: bug, patch
